version: '3'
services:
    # client:
    #     build: 
    #         context: .
    #         dockerfile: docker/web/Dockerfile
    #     ports:
    #         - "3000:3000"
    #     volumes:
    #         - .:/code
    #         - node_modules:/code/node_modules
    #     command: npm run serve
    #     depends_on:
    #         - api
    #     tty: true
    api:
        build: 
            context: .
            dockerfile: docker/api/Dockerfile
        volumes:
            - ./api:/code
            - node_modules:/code/node_modules
        command: npm run start:dev
        # depends_on:
        #     - db
        tty: true
    # db:
    #     build: 
    #         context: .
    #         dockerfile: docker/db/Dockerfile
    #     volumes:
    #         - ./tmp/db:/data/db
volumes:
    node_modules:
