version: '3'
services:
    api:
        build: 
            context: ./api
        ports:
            - $PORT:$PORT
        volumes:
            - ./api:/home
            - api_node_modules:/home/node_modules
        command: npm start
        env_file: ./api/.env
        # depends_on:
        #     - db
        tty: true
    client:
        build: 
            context: ./client
        ports:
            - "${LOCAL_DEV_PORT}:8080"
        volumes:
            - ./client:/home
            - client_node_modules:/home/node_modules
        command: npm start
        env_file: ./client/.env
        depends_on:
            - api
        tty: true
    # db:
    #     build: 
    #         context: .
    #         dockerfile: docker/db/Dockerfile
    #     volumes:
    #         - ./tmp/db:/data/db
volumes:
    api_node_modules:
    client_node_modules:
