version: '3'
services:
    client:
        build: 
            context: ./client
        ports:
            - "8000:8000"
        volumes:
            - ./client:/code
            - client_node_modules:/code/node_modules
        command: npm start
        depends_on:
            - api
        tty: true
    api:
        build: 
            context: ./api
        ports:
            - $PORT:$PORT
        volumes:
            - ./api:/code
            - api_node_modules:/code/node_modules
        command: npm start
        # env_file: ./api/.env
        # depends_on:
        #     - db
        tty: true
    # db:
    #     build: 
    #         context: .
    #         dockerfile: docker/db/Dockerfile
    #     volumes:
    #         - ./tmp/db:/data/db
volumes:
    api_node_modules:
    client_node_modules:
